import type { Metadata } from "next";
import { Providers } from "@/providers/themeProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Eventum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          <div className="bg-background min-h-screen">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
